spring:
  application:
    name: RoadTo500

  datasource:
    url: jdbc:postgresql://localhost:5432/roadto500
    username: postgres
    password: 11joshua
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: -1

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true

server:
  port: 8080